from nnlibrary.auto_diff_fast.forward_mode.abstractions import FrowardUniOperation
from nnlibrary.auto_diff_fast.forward_mode.abstractions import ForwardBiOperation
from nnlibrary.auto_diff_fast.forward_mode.forward_mode import ForwardMode

from nnlibrary.auto_diff_fast.forward_mode import special_vars
from nnlibrary.auto_diff_fast.forward_mode import math_ops
